# Generated by Django 3.0.8 on 2021-03-23 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='accounts_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ac_date', models.DateTimeField(auto_now_add=True)),
                ('ac_ref', models.CharField(blank=True, default=0, max_length=10)),
                ('cust_id', models.IntegerField(blank=True, default=0)),
                ('sup_id', models.IntegerField(blank=True, default=0)),
                ('ac_discription', models.CharField(max_length=225)),
                ('ac_debit', models.FloatField(blank=True, default=0)),
                ('ac_credit', models.FloatField(blank=True, default=0)),
                ('ac_balance', models.FloatField(blank=True, default=0)),
                ('p_ref', models.CharField(blank=True, max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='cust_registration_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(blank=True, default=0, max_length=24)),
                ('lname', models.CharField(blank=True, default=0, max_length=24)),
                ('address', models.CharField(blank=True, default=0, max_length=253)),
                ('contact1', models.CharField(blank=True, default=0, max_length=24)),
                ('alt_contact', models.CharField(blank=True, default=0, max_length=24)),
                ('dest_contact', models.CharField(blank=True, default=0, max_length=24)),
                ('dest_ref', models.CharField(blank=True, default=0, max_length=256)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('ref_person_name', models.CharField(blank=True, default=0, max_length=225)),
                ('ref_person_contact', models.CharField(blank=True, default=0, max_length=225)),
                ('home_address', models.CharField(blank=True, default=0, max_length=225)),
                ('description', models.CharField(blank=True, default=0, max_length=225)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('passport_no', models.CharField(blank=True, max_length=16)),
                ('dob', models.DateField(blank=True, null=True)),
                ('passport_expiry', models.DateField(blank=True, null=True)),
                ('uid', models.CharField(blank=True, max_length=36)),
            ],
        ),
        migrations.CreateModel(
            name='product_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(blank=True, max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_date', models.DateTimeField(auto_now_add=True)),
                ('cust_name', models.CharField(blank=True, max_length=225)),
                ('cust_id', models.IntegerField(blank=True, default=0)),
                ('product_id', models.IntegerField(blank=True, default=0)),
                ('product_name', models.CharField(blank=True, default=0, max_length=225)),
                ('sup_name', models.CharField(blank=True, default=0, max_length=225)),
                ('sup_id', models.IntegerField(blank=True, default=0)),
                ('purchase_rate', models.FloatField(blank=True, default=0)),
                ('sales_price', models.FloatField(blank=True, default=0)),
                ('paid_amount', models.FloatField(blank=True, default=0)),
                ('balance', models.FloatField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='suppliers_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sup_name', models.CharField(blank=True, max_length=225)),
                ('sup_address', models.TextField(blank=True)),
                ('sup_contact', models.IntegerField(blank=True)),
                ('sup_contact2', models.IntegerField(blank=True)),
                ('sup_email', models.EmailField(blank=True, max_length=254)),
                ('web', models.CharField(blank=True, max_length=225)),
            ],
        ),
    ]
