# Generated by Django 3.0.8 on 2021-04-11 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='saved_sales_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_date', models.DateTimeField(auto_now_add=True)),
                ('cust_name', models.CharField(blank=True, max_length=225)),
                ('cust_id', models.IntegerField(blank=True, default=0)),
                ('product_id', models.IntegerField(blank=True, default=0)),
                ('product_name', models.CharField(blank=True, default=0, max_length=225)),
                ('sup_name', models.CharField(blank=True, default=0, max_length=225)),
                ('sup_id', models.IntegerField(blank=True, default=0)),
                ('purchase_rate', models.FloatField(blank=True, default=0)),
                ('sales_price', models.FloatField(blank=True, default=0)),
                ('paid_amount', models.FloatField(blank=True, default=0)),
                ('balance', models.FloatField(blank=True, default=0)),
                ('pax_f_name', models.CharField(blank=True, default=0, max_length=225)),
                ('pax_l_name', models.CharField(blank=True, default=0, max_length=225)),
            ],
        ),
    ]
