# Generated by Django 3.0.8 on 2021-03-23 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts_table',
            name='test1',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
