# Generated by Django 3.0.8 on 2021-04-14 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_saved_sales_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='saved_data_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
