# Generated by Django 3.0.8 on 2021-03-14 09:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_cust_registration_table_passport_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='cust_registration_table',
            name='dob',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
