# Generated by Django 3.0.8 on 2021-04-19 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_sales_saved_data_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_table',
            name='p_category',
            field=models.CharField(blank=True, max_length=225),
        ),
    ]
