# Generated by Django 3.0.8 on 2021-04-07 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_remove_accounts_table_test1'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='pax_f_name',
            field=models.CharField(blank=True, default=0, max_length=225),
        ),
        migrations.AddField(
            model_name='sales',
            name='pax_l_name',
            field=models.CharField(blank=True, default=0, max_length=225),
        ),
    ]
