# Generated by Django 3.0.8 on 2021-03-14 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20210314_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cust_registration_table',
            name='uid',
            field=models.CharField(blank=True, max_length=36),
        ),
    ]
