# Generated by Django 3.0.8 on 2021-04-09 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20210407_0843'),
    ]

    operations = [
        migrations.CreateModel(
            name='saved_services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pax_f_name', models.CharField(blank=True, max_length=50, null=True)),
                ('pax_l_name', models.CharField(blank=True, max_length=50, null=True)),
                ('service', models.CharField(blank=True, max_length=50, null=True)),
                ('suppliers', models.CharField(blank=True, max_length=50, null=True)),
                ('purchase_rate', models.FloatField(blank=True, default=0)),
                ('sales_rate', models.FloatField(blank=True, default=0)),
                ('passport_no', models.CharField(blank=True, max_length=50, null=True)),
                ('passport_expiry_date', models.DateField(blank=True, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('dest_contact', models.CharField(blank=True, max_length=50, null=True)),
                ('dest_address', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
