# Generated by Django 3.0.8 on 2021-04-09 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_saved_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='saved_services',
            name='cust_id',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='saved_services',
            name='cust_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
