# Generated by Django 3.0.8 on 2021-03-14 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20210314_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cust_registration_table',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
