# Generated by Django 3.0.8 on 2021-03-14 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20210314_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cust_registration_table',
            name='passport_expiry',
            field=models.DateField(blank=True, null=True),
        ),
    ]
