# Generated by Django 3.0.8 on 2021-03-19 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20210314_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='sup_id',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
