# Generated by Django 3.0.8 on 2021-03-19 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_sales_sup_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounts_table',
            old_name='ac_credit',
            new_name='ac_debit1',
        ),
    ]
