# Generated by Django 3.0.8 on 2021-03-19 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20210319_2158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounts_table',
            old_name='ac_debit',
            new_name='ac_credit',
        ),
    ]
