# Generated by Django 3.0.8 on 2021-03-19 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_auto_20210319_2202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounts_table',
            old_name='ac_debit1',
            new_name='ac_debit',
        ),
    ]
