# Generated by Django 3.0.8 on 2021-03-19 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_auto_20210319_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts_table',
            name='sup_id',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
