# Generated by Django 3.0.8 on 2021-03-22 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_accounts_table_sup_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cust_registration_table',
            name='alt_contact',
            field=models.CharField(blank=True, default=0, max_length=24),
        ),
        migrations.AlterField(
            model_name='cust_registration_table',
            name='contact1',
            field=models.CharField(blank=True, default=0, max_length=24),
        ),
        migrations.AlterField(
            model_name='cust_registration_table',
            name='dest_contact',
            field=models.CharField(blank=True, default=0, max_length=24),
        ),
    ]
