# Generated by Django 3.0.8 on 2021-03-22 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_auto_20210322_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts_table',
            name='ac_credit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=99),
        ),
        migrations.AlterField(
            model_name='accounts_table',
            name='ac_debit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=99),
        ),
    ]
