# Generated by Django 3.0.8 on 2021-03-22 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_auto_20210322_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts_table',
            name='ac_credit',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='accounts_table',
            name='ac_debit',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
