# Generated by Django 3.0.8 on 2021-03-23 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_auto_20210322_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts_table',
            name='ac_credit',
            field=models.CharField(blank=True, default=0, max_length=225),
        ),
        migrations.AlterField(
            model_name='accounts_table',
            name='ac_debit',
            field=models.CharField(blank=True, default=0, max_length=225),
        ),
    ]
