# Generated by Django 3.0.8 on 2021-03-23 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_auto_20210323_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts_table',
            name='ac_credit',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='accounts_table',
            name='ac_debit',
            field=models.FloatField(null=True),
        ),
    ]
