# Generated by Django 3.0.8 on 2021-03-23 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_auto_20210323_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts_table',
            name='ac_credit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='accounts_table',
            name='ac_debit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, null=True),
        ),
    ]
