# Generated by Django 3.0.8 on 2021-03-23 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_auto_20210323_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts_table',
            name='ac_credit',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='accounts_table',
            name='ac_debit',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
