# Generated by Django 3.0.8 on 2021-03-23 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_auto_20210323_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts_table',
            name='ac_credit',
            field=models.DecimalField(blank=0, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='accounts_table',
            name='ac_debit',
            field=models.DecimalField(blank=0, decimal_places=2, max_digits=10, null=True),
        ),
    ]
