# Generated by Django 3.0.8 on 2021-03-23 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_auto_20210323_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts_table',
            name='ac_credit',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='accounts_table',
            name='ac_debit',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
