# Generated by Django 3.0.8 on 2021-03-23 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_auto_20210323_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts_table',
            name='test',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
    ]
