# Generated by Django 3.0.8 on 2021-03-07 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cus_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=24)),
                ('address', models.CharField(max_length=253)),
                ('contact1', models.IntegerField(blank=True, null=True)),
                ('alt_contact', models.IntegerField(blank=True, null=True)),
                ('dest_contact', models.IntegerField(blank=True, null=True)),
                ('dest_ref', models.CharField(max_length=256)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('ref_person_name', models.CharField(max_length=225)),
                ('ref_person_contact', models.CharField(max_length=225)),
                ('home_address', models.CharField(max_length=225)),
                ('description', models.CharField(max_length=225)),
            ],
        ),
    ]
