# Generated by Django 3.0.8 on 2021-03-07 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cus_table',
            new_name='cust_table',
        ),
    ]
