# Generated by Django 3.0.8 on 2021-03-07 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20210307_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cust_table',
            name='address',
        ),
        migrations.RemoveField(
            model_name='cust_table',
            name='alt_contact',
        ),
        migrations.RemoveField(
            model_name='cust_table',
            name='contact1',
        ),
        migrations.RemoveField(
            model_name='cust_table',
            name='description',
        ),
        migrations.RemoveField(
            model_name='cust_table',
            name='dest_contact',
        ),
        migrations.RemoveField(
            model_name='cust_table',
            name='dest_ref',
        ),
        migrations.RemoveField(
            model_name='cust_table',
            name='email',
        ),
        migrations.RemoveField(
            model_name='cust_table',
            name='home_address',
        ),
        migrations.RemoveField(
            model_name='cust_table',
            name='ref_person_contact',
        ),
        migrations.RemoveField(
            model_name='cust_table',
            name='ref_person_name',
        ),
    ]
