# Generated by Django 3.0.8 on 2021-03-07 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20210307_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='cust_table',
            name='address',
            field=models.CharField(default=0, max_length=253),
        ),
        migrations.AddField(
            model_name='cust_table',
            name='alt_contact',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cust_table',
            name='contact1',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cust_table',
            name='description',
            field=models.CharField(default=0, max_length=225),
        ),
        migrations.AddField(
            model_name='cust_table',
            name='dest_contact',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cust_table',
            name='dest_ref',
            field=models.CharField(default=0, max_length=256),
        ),
        migrations.AddField(
            model_name='cust_table',
            name='email',
            field=models.EmailField(blank=True, default=0, max_length=254),
        ),
        migrations.AddField(
            model_name='cust_table',
            name='home_address',
            field=models.CharField(default=0, max_length=225),
        ),
        migrations.AddField(
            model_name='cust_table',
            name='ref_person_contact',
            field=models.CharField(default=0, max_length=225),
        ),
        migrations.AddField(
            model_name='cust_table',
            name='ref_person_name',
            field=models.CharField(default=0, max_length=225),
        ),
        migrations.AlterField(
            model_name='cust_table',
            name='fname',
            field=models.CharField(default=0, max_length=24),
        ),
    ]
