# Generated by Django 3.0.8 on 2021-03-08 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20210307_2337'),
    ]

    operations = [
        migrations.CreateModel(
            name='cust_registration_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(default=0, max_length=24)),
                ('address', models.CharField(default=0, max_length=253)),
                ('contact1', models.IntegerField(blank=True, default=0, null=True)),
                ('alt_contact', models.IntegerField(blank=True, default=0, null=True)),
                ('dest_contact', models.IntegerField(blank=True, default=0, null=True)),
                ('dest_ref', models.CharField(default=0, max_length=256)),
                ('email', models.EmailField(blank=True, default=0, max_length=254)),
                ('ref_person_name', models.CharField(default=0, max_length=225)),
                ('ref_person_contact', models.CharField(default=0, max_length=225)),
                ('home_address', models.CharField(default=0, max_length=225)),
                ('description', models.CharField(default=0, max_length=225)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
