# Generated by Django 3.0.8 on 2021-03-08 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_cust_registration_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cust_registration_table',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
