# Generated by Django 3.0.8 on 2021-03-08 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20210308_0826'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cust_table',
        ),
    ]
