# Generated by Django 3.0.8 on 2021-03-08 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_delete_cust_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=225)),
            ],
        ),
    ]
