# Generated by Django 3.0.8 on 2021-03-08 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_product_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='suppliers_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sup_name', models.CharField(blank=True, max_length=225)),
                ('sup_address', models.TextField(blank=True)),
                ('sup_contact', models.IntegerField(blank=True)),
                ('sup_contact2', models.IntegerField(blank=True)),
                ('sup_email', models.EmailField(blank=True, max_length=254)),
                ('web', models.CharField(blank=True, max_length=225)),
            ],
        ),
    ]
