# Generated by Django 3.0.8 on 2021-03-08 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_suppliers_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_date', models.DateTimeField(auto_now_add=True)),
                ('cust_name', models.CharField(blank=True, max_length=225)),
                ('product_id', models.IntegerField(blank=True)),
                ('product_name', models.CharField(max_length=225)),
                ('sup_name', models.CharField(max_length=225)),
                ('sales_price', models.FloatField()),
                ('purchase_rate', models.FloatField()),
            ],
        ),
    ]
