# Generated by Django 3.0.8 on 2021-03-08 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='cust_registration_table',
            name='lname',
            field=models.CharField(default=0, max_length=24),
        ),
    ]
