# Generated by Django 3.0.8 on 2021-03-08 20:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_remove_sales_sales_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='sales_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
