# Generated by Django 3.0.8 on 2021-03-10 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_sales_sales_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='accounts_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ac_date', models.DateTimeField(auto_now_add=True)),
                ('ac_ref', models.CharField(blank=True, max_length=10)),
                ('ac_discription', models.CharField(max_length=1000)),
                ('ac_debit', models.FloatField(blank=True, default=0)),
                ('ac_credit', models.FloatField(blank=True, default=0)),
                ('ac_balance', models.FloatField(blank=True, default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='sales',
            name='purchase_rate',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='sales',
            name='sales_price',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
