# Generated by Django 3.0.8 on 2021-03-10 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_auto_20210310_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts_table',
            name='cust_id',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
