# Generated by Django 3.0.8 on 2021-03-12 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_accounts_table_cust_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='paid_amount',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
