# Generated by Django 3.0.8 on 2021-03-12 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_sales_paid_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='balance',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
