# Generated by Django 3.0.8 on 2021-03-12 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_sales_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='cust_id',
            field=models.IntegerField(blank=True, default=0, max_length=24),
        ),
    ]
