# Generated by Django 3.0.8 on 2021-03-13 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_sales_cust_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts_table',
            name='p_ref',
            field=models.CharField(blank=True, max_length=225),
        ),
    ]
