# Generated by Django 3.0.8 on 2021-03-13 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_accounts_table_p_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts_table',
            name='ac_ref',
            field=models.CharField(blank=True, default=0, max_length=10),
        ),
    ]
