# Generated by Django 3.0.8 on 2021-03-14 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_auto_20210313_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='cust_registration_table',
            name='dob',
            field=models.DateField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='cust_registration_table',
            name='passport_expiry',
            field=models.DateField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='cust_registration_table',
            name='passport_no',
            field=models.CharField(blank=True, default=0, max_length=16),
        ),
        migrations.AddField(
            model_name='cust_registration_table',
            name='uid',
            field=models.CharField(blank=True, default=0, max_length=20),
        ),
    ]
