# Generated by Django 3.0.8 on 2021-03-14 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_remove_cust_registration_table_passport_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cust_registration_table',
            name='address',
            field=models.CharField(blank=True, default=0, max_length=253),
        ),
        migrations.AlterField(
            model_name='cust_registration_table',
            name='description',
            field=models.CharField(blank=True, default=0, max_length=225),
        ),
        migrations.AlterField(
            model_name='cust_registration_table',
            name='dest_ref',
            field=models.CharField(blank=True, default=0, max_length=256),
        ),
        migrations.AlterField(
            model_name='cust_registration_table',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='cust_registration_table',
            name='fname',
            field=models.CharField(blank=True, default=0, max_length=24),
        ),
        migrations.AlterField(
            model_name='cust_registration_table',
            name='home_address',
            field=models.CharField(blank=True, default=0, max_length=225),
        ),
        migrations.AlterField(
            model_name='cust_registration_table',
            name='lname',
            field=models.CharField(blank=True, default=0, max_length=24),
        ),
        migrations.AlterField(
            model_name='cust_registration_table',
            name='ref_person_contact',
            field=models.CharField(blank=True, default=0, max_length=225),
        ),
        migrations.AlterField(
            model_name='cust_registration_table',
            name='ref_person_name',
            field=models.CharField(blank=True, default=0, max_length=225),
        ),
    ]
