# Generated by Django 3.0.8 on 2021-03-14 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_auto_20210314_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='product_id',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
