# Generated by Django 3.0.8 on 2021-03-14 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_auto_20210314_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='product_name',
            field=models.CharField(blank=True, default=0, max_length=225),
        ),
        migrations.AlterField(
            model_name='sales',
            name='sup_name',
            field=models.CharField(blank=True, default=0, max_length=225),
        ),
    ]
