# Generated by Django 3.0.8 on 2021-03-14 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_auto_20210314_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts_table',
            name='ac_discription',
            field=models.CharField(max_length=225),
        ),
    ]
