# Generated by Django 3.0.8 on 2021-03-14 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0032_cust_registration_table_passport_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cust_registration_table',
            name='passport_no',
        ),
    ]
