# Generated by Django 3.0.8 on 2021-03-14 08:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0033_remove_cust_registration_table_passport_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='cust_registration_table',
            name='passport_no',
            field=models.CharField(default=django.utils.timezone.now, max_length=225),
            preserve_default=False,
        ),
    ]
