# Generated by Django 3.0.8 on 2021-03-14 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0034_cust_registration_table_passport_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cust_registration_table',
            name='address',
        ),
        migrations.RemoveField(
            model_name='cust_registration_table',
            name='alt_contact',
        ),
        migrations.RemoveField(
            model_name='cust_registration_table',
            name='contact1',
        ),
        migrations.RemoveField(
            model_name='cust_registration_table',
            name='date',
        ),
        migrations.RemoveField(
            model_name='cust_registration_table',
            name='description',
        ),
        migrations.RemoveField(
            model_name='cust_registration_table',
            name='dest_contact',
        ),
        migrations.RemoveField(
            model_name='cust_registration_table',
            name='dest_ref',
        ),
        migrations.RemoveField(
            model_name='cust_registration_table',
            name='email',
        ),
        migrations.RemoveField(
            model_name='cust_registration_table',
            name='home_address',
        ),
        migrations.RemoveField(
            model_name='cust_registration_table',
            name='lname',
        ),
        migrations.RemoveField(
            model_name='cust_registration_table',
            name='passport_no',
        ),
        migrations.RemoveField(
            model_name='cust_registration_table',
            name='ref_person_contact',
        ),
        migrations.RemoveField(
            model_name='cust_registration_table',
            name='ref_person_name',
        ),
    ]
