# Generated by Django 3.0.8 on 2021-03-14 08:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0035_auto_20210314_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='cust_registration_table',
            name='address',
            field=models.CharField(blank=True, default=0, max_length=253),
        ),
        migrations.AddField(
            model_name='cust_registration_table',
            name='alt_contact',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cust_registration_table',
            name='contact1',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cust_registration_table',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cust_registration_table',
            name='description',
            field=models.CharField(blank=True, default=0, max_length=225),
        ),
        migrations.AddField(
            model_name='cust_registration_table',
            name='dest_contact',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cust_registration_table',
            name='dest_ref',
            field=models.CharField(blank=True, default=0, max_length=256),
        ),
        migrations.AddField(
            model_name='cust_registration_table',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='cust_registration_table',
            name='home_address',
            field=models.CharField(blank=True, default=0, max_length=225),
        ),
        migrations.AddField(
            model_name='cust_registration_table',
            name='lname',
            field=models.CharField(blank=True, default=0, max_length=24),
        ),
        migrations.AddField(
            model_name='cust_registration_table',
            name='ref_person_contact',
            field=models.CharField(blank=True, default=0, max_length=225),
        ),
        migrations.AddField(
            model_name='cust_registration_table',
            name='ref_person_name',
            field=models.CharField(blank=True, default=0, max_length=225),
        ),
    ]
