# Generated by Django 3.0.8 on 2021-03-14 08:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0037_auto_20210314_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliers_table',
            name='sup_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='suppliers_table',
            name='sup_contact',
            field=models.IntegerField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suppliers_table',
            name='sup_contact2',
            field=models.IntegerField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suppliers_table',
            name='sup_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='suppliers_table',
            name='web',
            field=models.CharField(blank=True, max_length=225),
        ),
    ]
