# Generated by Django 3.0.8 on 2021-03-14 08:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0039_auto_20210314_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='cust_id',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='sales',
            name='cust_name',
            field=models.CharField(blank=True, max_length=225),
        ),
        migrations.AddField(
            model_name='sales',
            name='paid_amount',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='sales',
            name='product_id',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='sales',
            name='product_name',
            field=models.CharField(blank=True, default=0, max_length=225),
        ),
        migrations.AddField(
            model_name='sales',
            name='purchase_rate',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='sales',
            name='sales_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sales',
            name='sales_price',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='sales',
            name='sup_name',
            field=models.CharField(blank=True, default=0, max_length=225),
        ),
    ]
