# Generated by Django 3.0.8 on 2021-03-14 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0040_auto_20210314_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounts_table',
            name='ac_balance',
        ),
        migrations.RemoveField(
            model_name='accounts_table',
            name='ac_credit',
        ),
        migrations.RemoveField(
            model_name='accounts_table',
            name='ac_date',
        ),
        migrations.RemoveField(
            model_name='accounts_table',
            name='ac_debit',
        ),
        migrations.RemoveField(
            model_name='accounts_table',
            name='ac_discription',
        ),
        migrations.RemoveField(
            model_name='accounts_table',
            name='ac_ref',
        ),
        migrations.RemoveField(
            model_name='accounts_table',
            name='cust_id',
        ),
    ]
