# Generated by Django 3.0.8 on 2021-03-14 08:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0041_auto_20210314_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts_table',
            name='ac_balance',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='accounts_table',
            name='ac_credit',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='accounts_table',
            name='ac_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accounts_table',
            name='ac_debit',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='accounts_table',
            name='ac_discription',
            field=models.CharField(default=django.utils.timezone.now, max_length=225),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accounts_table',
            name='ac_ref',
            field=models.CharField(blank=True, default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='accounts_table',
            name='cust_id',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
